# Generated by Django 2.2.5 on 2019-10-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20191014_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
