# Generated by Django 2.2.5 on 2019-10-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_article_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='moderation',
            field=models.BooleanField(default=False, verbose_name='Модерация'),
        ),
    ]
