# Generated by Django 2.2.5 on 2019-10-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_article_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(default='', upload_to='img/title_article'),
        ),
    ]
