# Generated by Django 2.2.5 on 2019-10-17 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_auto_20191017_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogapp.Category', verbose_name='Категория статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(default='', upload_to='img/title_article', verbose_name='Картинка статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.CharField(default='', max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=200, verbose_name='Текст комментария'),
        ),
    ]
